version: "3.9"
services:
  mongodb:
    image: mongo
    container_name: project_base_mongodb
    ports:
      - ${PROJECT_MONGO_PORT}:27017
    volumes:
      - ${PROJECT_MONGODB_PATH}/data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PROJECT_MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${PROJECT_MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_URI=mongodb://mongodb:27017
    restart: always
    # networks:
    #   - backend-network
    # network_mode: "host"