export const ORDER_TOPIC = {
  FLORIST: {
    LSIT: "order.florist.orderList",
    LIST_BY_MONTH: "order.florist.orderListByMonth",
    SHOP_USER_ORDER_STATUS: "order.florist.checkShopUserOrderStatus",
    REG_IN: "order.florist.orderRegIn",
    DETAIL: "order.florist.orderDetail",
    MODIFY: "order.florist.orderModify",
    ACCEPT: "order.florist.orderAccept",
    REJECT: "order.florist.orderReject",
    CONFIRM: "order.florist.orderConfirm",
    PICKUP_REQUEST: "order.florist.orderPickupRequest",
    COMPLETE: "order.florist.orderComplete",
    CANCEL: "order.florist.orderCencel",
    INFO: "order.florist.orderInfo",
  },
  USER: {
    CURRENT: "order.user.orderCurrent",
    DETAIL: "order.user.orderDetail",
    REG_IN: "order.user.orderRegIn",
    CONSULTING: "order.user.orderRegInWithConsulting",
    QUICK_ORDER: "order.user.orderRegInWithQuickOrder",
    CANCEL: "order.user.orderCencel",
    REQUEST_PAYMENT: "order.user.orderRequestPayment",
    INFO: "order.user.orderInfo",
    LIST: "order.user.orderList",
    REVIEW_LIST: "order.user.orderReviewList",
    REVIEW_DETAIL: "order.user.orderReviewDetail",
    REVIEW_REG_IN: "order.user.orderReviewRegIn",
  },
};

export const ORDER_TOPICS = [
  ORDER_TOPIC.FLORIST.LSIT,
  ORDER_TOPIC.FLORIST.LIST_BY_MONTH,
  ORDER_TOPIC.FLORIST.SHOP_USER_ORDER_STATUS,
  ORDER_TOPIC.FLORIST.REG_IN,
  ORDER_TOPIC.FLORIST.DETAIL,
  ORDER_TOPIC.FLORIST.MODIFY,
  ORDER_TOPIC.FLORIST.ACCEPT,
  ORDER_TOPIC.FLORIST.REJECT,
  ORDER_TOPIC.FLORIST.CONFIRM,
  ORDER_TOPIC.FLORIST.PICKUP_REQUEST,
  ORDER_TOPIC.FLORIST.COMPLETE,
  ORDER_TOPIC.FLORIST.CANCEL,
  ORDER_TOPIC.FLORIST.INFO,
  ORDER_TOPIC.USER.CURRENT,
  ORDER_TOPIC.USER.DETAIL,
  ORDER_TOPIC.USER.REG_IN,
  ORDER_TOPIC.USER.CONSULTING,
  ORDER_TOPIC.USER.QUICK_ORDER,
  ORDER_TOPIC.USER.CANCEL,
  ORDER_TOPIC.USER.REQUEST_PAYMENT,
  ORDER_TOPIC.USER.INFO,
  ORDER_TOPIC.USER.LIST,
  ORDER_TOPIC.USER.REVIEW_LIST,
  ORDER_TOPIC.USER.REVIEW_DETAIL,
  ORDER_TOPIC.USER.REVIEW_REG_IN,
];
